// Flutter Windows platform plugin wiring DisplayDaemon to the Dart side.
//
// This follows the standard shape of a `flutter create --template=plugin`
// Windows plugin (a FlutterPlugin subclass registered from
// RegisterWithRegistrar and a MethodChannel named
// "com.elliotoffice.projection_mapper/display"). It is written to be dropped
// into `windows/flutter/generated_plugins.cmake` registration once the
// Flutter Windows embedder scaffolding is generated by `flutter create`.

#include "display_daemon.h"

#include <flutter/method_channel.h>
#include <flutter/plugin_registrar_windows.h>
#include <flutter/standard_method_codec.h>

#include <memory>

namespace projection_mapper {

namespace {

constexpr char kChannelName[] = "com.elliotoffice.projection_mapper/display";

flutter::EncodableMap DisplayInfoToMap(const DisplayInfo& d) {
  return flutter::EncodableMap{
      {flutter::EncodableValue("id"), flutter::EncodableValue(d.id)},
      {flutter::EncodableValue("deviceName"), flutter::EncodableValue(d.device_name)},
      {flutter::EncodableValue("x"), flutter::EncodableValue(d.x)},
      {flutter::EncodableValue("y"), flutter::EncodableValue(d.y)},
      {flutter::EncodableValue("width"), flutter::EncodableValue(d.width)},
      {flutter::EncodableValue("height"), flutter::EncodableValue(d.height)},
      {flutter::EncodableValue("isPrimary"), flutter::EncodableValue(d.is_primary)},
  };
}

}  // namespace

class DisplayDaemonPlugin : public flutter::Plugin {
 public:
  static void RegisterWithRegistrar(flutter::PluginRegistrarWindows* registrar) {
    auto channel = std::make_unique<flutter::MethodChannel<flutter::EncodableValue>>(
        registrar->messenger(), kChannelName,
        &flutter::StandardMethodCodec::GetInstance());

    auto plugin = std::make_unique<DisplayDaemonPlugin>();
    auto* plugin_ptr = plugin.get();

    channel->SetMethodCallHandler(
        [plugin_ptr](const auto& call, auto result) {
          plugin_ptr->HandleMethodCall(call, std::move(result));
        });

    registrar->AddPlugin(std::move(plugin));
  }

  DisplayDaemonPlugin() = default;
  ~DisplayDaemonPlugin() override = default;

 private:
  void HandleMethodCall(
      const flutter::MethodCall<flutter::EncodableValue>& call,
      std::unique_ptr<flutter::MethodResult<flutter::EncodableValue>> result) {
    const std::string& method = call.method_name();

    if (method == "listDisplays") {
      auto displays = daemon_.ListDisplays();
      flutter::EncodableList list;
      for (const auto& d : displays) {
        list.push_back(flutter::EncodableValue(DisplayInfoToMap(d)));
      }
      result->Success(flutter::EncodableValue(list));
      return;
    }

    if (method == "sendToProjector") {
      const auto* args = std::get_if<flutter::EncodableMap>(call.arguments());
      if (args == nullptr) {
        result->Error("bad_args", "Expected {displayId: string}");
        return;
      }
      auto it = args->find(flutter::EncodableValue("displayId"));
      if (it == args->end()) {
        result->Error("bad_args", "Missing displayId");
        return;
      }
      const auto& display_id = std::get<std::string>(it->second);
      int64_t hwnd = daemon_.SendToProjector(display_id);
      if (hwnd == 0) {
        result->Error("display_not_found",
                       "No connected display matches id " + display_id);
        return;
      }
      result->Success(flutter::EncodableValue(hwnd));
      return;
    }

    if (method == "closeProjector") {
      daemon_.CloseProjectorWindow();
      result->Success();
      return;
    }

    if (method == "hasActiveProjectorWindow") {
      result->Success(flutter::EncodableValue(daemon_.HasActiveProjectorWindow()));
      return;
    }

    result->NotImplemented();
  }

  DisplayDaemon daemon_;
};

}  // namespace projection_mapper

void DisplayDaemonPluginRegisterWithRegistrar(
    FlutterDesktopPluginRegistrarRef registrar) {
  auto* windows_registrar =
      flutter::PluginRegistrarManager::GetInstance()
          ->GetRegistrar<flutter::PluginRegistrarWindows>(registrar);
  projection_mapper::DisplayDaemonPlugin::RegisterWithRegistrar(windows_registrar);
}
